version: "3"
services:
  rabbit:
    image: rabbitmq:management
    ports:
        - "15672:15672"
        - "5672:5672"
    healthcheck:
      test: ["CMD-SHELL", "rabbitmqctl status"]
      interval: 30s
      timeout: 30s
      retries: 3

  carrot:
    image: golang:1.14
    volumes:
      - ./:/go/src/github.com/ar3s3ru/go-carrot:delegated
    working_dir: /go/src/github.com/ar3s3ru/go-carrot
    tty: true
    depends_on:
      - rabbit
