on: push

name: Pipeline

jobs:
  test:
    name: Golang 1.13
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install Golang
        uses: actions/setup-go@v2-beta
        with:
          go-version: '1.13'

      - name: Run go test
        run: go test -race -covermode=atomic -coverprofile=coverage.txt ./...

      - name: Upload coverage report
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt
          flags: unit
          fail_ci_if_error: true
